// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addusertoken.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addUserToken = `-- name: AddUserToken :exec
UPDATE users
SET token = $2
WHERE id = $1
`

type AddUserTokenParams struct {
	ID    uuid.UUID
	Token string
}

func (q *Queries) AddUserToken(ctx context.Context, arg AddUserTokenParams) error {
	_, err := q.db.ExecContext(ctx, addUserToken, arg.ID, arg.Token)
	return err
}
