// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getuserfromtoken.sql

package database

import (
	"context"
	"database/sql"
)

const getUserFromToken = `-- name: GetUserFromToken :one
SELECT id, created_at, updated_at, email, hashed_password, token FROM users
WHERE token = $1
`

func (q *Queries) GetUserFromToken(ctx context.Context, token sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.Token,
	)
	return i, err
}
